### ISSUE TITLE
Slide Layout with Long Record Names

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#147]
Wanted to report that for a long time but always forgot. As seen [here](https://github.com/openPMD/openPMD-viewer/issues/146#issue-209782850) we like to have rather long field and particle attribute names which breaks the layout a bit. Can one adjust it a little so it is more flexible with regards to long record names?

Also the range "number input" boxes in the `Plotting` options are sometimes too small in width to see all numbers (e.g. "19" for "1e19") one entered. The last point might also just be a Chrome issue.

**Comment by RemiLehe** [comment]
Thanks for reporting this problem!

Regarding the size of the field panel: one quick fix would be to just make the panel wider (actually just as wide as the particle panel on the other side). It would contain your current long record names, but would not be robust if you have even longer record name.
With `ipywidgets`, it is also possible to let the notebook decide how wide the box should be, but then it annoyingly changes the size of the box when I go from the field options to the plotting options. (or, for the particle panel, when I go from the particle options to the selection options, or to the plotting options). This is why I used fixed size instead. 

Regarding the number input boxes, there are meant to be wider (see the image below for instance, which is what I get on my computer), but I have observed that these boxes are small when the version of ipywidgets is different. I thought I had fixed the problem, but apparently not.
![screen shot 2017-02-24 at 1 12 53 pm](https://cloud.githubusercontent.com/assets/6685781/23321156/f8625fca-fa92-11e6-8c12-26bf99a243b9.png)
Could you let me know what version you currently have for:
- Python
- ipywidgets
- openPMD-viewer
so that I can try to reproduce the error.

**Comment by ax3l** [comment]
@HighIander can you report your browser and software versions you used, where we saw the problem with entering a field's plotting ranges last week?

**Comment by RemiLehe** [comment]
Regarding the problem of the size of the text boxes (being too small): it is seems that this problem only happens in Safari. I'm looking into this, but in the meanwhile, an easy fix is to simply use Firefox instead.

**Comment by ax3l** [comment]
For that case, we saw it in Chrome on Linux I think.

**Comment by RemiLehe** [comment]
Ok, thanks for the info. Does Firefox fix the issue for you, though?

**Comment by ax3l** [comment]
Hm, at least I can't reproduce the number-input issue. Here is a layout issue with fields:

**Chrome 55. on Linux**
![screenshot from 2017-03-03 15 21 40](https://cloud.githubusercontent.com/assets/1353258/23554481/8b7b6f6c-0025-11e7-8e5b-ca4844b61859.png)

**Firefox 45.6 on Linux**
![screenshot from 2017-03-03 15 23 09](https://cloud.githubusercontent.com/assets/1353258/23554499/9421fbb8-0025-11e7-92fd-5d783f02a3e2.png)

**Comment by RemiLehe** [comment]
FYI : this seems to be a [more general issue](https://github.com/ipython/ipywidgets/issues/1193)

**Comment by HighIander** [comment]
Hi, sorry for late reply! I am not sure if it is the same problem as the font size, but in Chrome I don't see any number in the input boxes, see below. I can blindly input data, though. Firefox fixes the issue.
![image](https://cloud.githubusercontent.com/assets/6409838/23694994/4cb64ae8-03dd-11e7-8b55-84d72393240b.png)

**Comment by ax3l** [comment]
thanks for reporting the issue in ipywidgets!
Are we already ipywidgets 6 compatible? If so, we can just update to fix ;)

**Comment by RemiLehe** [comment]
For the moment, ipywidgets 6 would considerably change the aspect of the panels in the slider. Also, it would be an issue for the long variable names that you have, since - so far - the boxes in ipywidgets 6 do not adapt to the size of the text that they contain.

**Comment by RemiLehe** [comment]
(The above remark is specifically of the `ToggleButtons` widget which we use to select e.g. the Field.)

**Comment by ax3l** [comment]
closed via #151
