### ISSUE TITLE
Slider: Naming Slice

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#148]
With "slice direction" in the `OpenPMDTimeSeries.slider` we actually mean the slice *normal*, don't we? Should we rename it, I find the term *direction* to be quite arbitrary in the widget (because a plane would need at least to base vectors pointing somewhere in the plane to span a slice).

**Comment by RemiLehe** [comment]
Yes, it is indeed the slice *normal*. 
One option would be to replace "Slice direction" by "Slice along:". The idea is that when the user wants an x-z slice, then he has to **slice** the data **along** y.

Would this be a good solution?

**Comment by RemiLehe** [comment]
Actually, please disregard my latest comment: in the end, I think "Slice along" is just as confusing as "Slice direction:".
So, I agree that "Slice perpendicular to" or "Slice orthogononal to" is clearer but it is also a bit too long for the GUI:
<img width="645" alt="screen shot 2017-03-01 at 8 28 29 am" src="https://cloud.githubusercontent.com/assets/6685781/23469759/65427106-fe59-11e6-99f2-2f0338fc6cd1.png">

Instead what, do you think of "Slicing through:" (a bit less clear, but also much shorter). Any other suggestion otherwise?

**Comment by ax3l** [comment]
Wuhu, yeas that's why I thought make it short and explicit with "slice normal:" specifying the normal of the slice :)


I would also rename "Coord" to "comp." or "component" since it's not necessarily along the same and can be confusing.

**Comment by RemiLehe** [comment]
OK, "Slice normal:" works. I'll prepare a PR for this.

Regarding changing "coord" to "comp.", the problem is that the `get_field` API uses "coord" (which is probably a badly chosen name, but we now have to stick to it for backwards compatibility). Of course, we can use a different name in the GUI and the API, but I would rather not. What do you think?

**Comment by ax3l** [comment]
I think lets open an issue and change coord to component in a major release, e.g. 1.0.0

**Comment by ax3l** [comment]
closed via #149
