### ISSUE TITLE
TimeSeries slider: Mouse Dragging and Time Label

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-viewer#158]
When using the OpenPMDTimeSeries slider, there is a discrepancy between the time given at the iteration slider and the one given as plot title.

UPDATE:
This is only caused when dragging the slider with the mouse. 

![openpmd_timebug](https://cloud.githubusercontent.com/assets/5121158/25712319/98a99f7c-30f1-11e7-9144-66614e64c729.png)

I used openPMDviewer with data from PIConGPU. I will further investigate this discrepancy and post it here.

**Comment by PrometheusPi** [comment]
This discrepancy **only occurs** when sliding the slider **with the mouse**. When using the plus and minus buttons, there is no discrepancy. 

Both particle and field plots are effected.

**Comment by PrometheusPi** [comment]
This seems to be an issue with dragging the slider with the mouse. 
Thus I will rename the title of this issue.

**Comment by PrometheusPi** [comment]
Perhaps #92 will outdate this issue

**Comment by ax3l** [comment]
Interesting widged behavior, it might be useful to post your browser version, ipywidged version and openPMD-viewer version, too

**Comment by RemiLehe** [comment]
Yes, Axel is correct: when moving the slider with the mouse, you can select any time (and this is what gets printed), but then openPMD-viewer selects the closest time available for the plot. 

Because the printed time on the side of the slider is done directly by ipywidgets (not by openPMD-viewer), I am not sure we can modify the time that gets printed without actually moving the cursor on the slider to one of the available times. But then, automatically moving the cursor might get annoying when a user is dragging the mouse continuously (especially if there is some delay).

So it looks like this would be a "won't fix", unless someone has a nice suggestion  on how to solve the above issues. @PrometheusPi Would that be fine with you?

**Comment by RemiLehe** [comment]
One possibility is to simply remove the printed time, but I am not sure if this is desirable either...

**Comment by PrometheusPi** [comment]
I use the most recent (stable) firefox 53.0 (64 bits) for Mac. 
 - matplotlib: `'2.0.0rc1'`
 - ipywidgets: `'5.2.2'`
 - open PMD viewer `0.3.3` (you are missing a `.__version__`)

Yes, the issue can be closed as *won't fix* it it is a  ipywidgets issue
