### ISSUE TITLE
Slider vanishing with Jupyter 5.2.0

### ISSUE THREAD

**Issue by n01r** [openPMD/openPMD-viewer#174]
I recently upgraded my Jupyter to kernel version 5.2.0 to use some nifty `nbextensions`. When I tried to use the openPMD slider again, at first, everything was shown normally but as soon as I picked a time step only the plots were shown but the slider widget had vanished.

I'm using Python 3.4.3 and Jupyter 5.2.0.

**Comment by RemiLehe** [comment]
Thanks for reporting this! Could you check which ipywidgets version you have?

**Comment by n01r** [comment]
Sure! I have version 7.0.2.

**Comment by RemiLehe** [comment]
OK. Could you try typing, in a terminal: 
```
jupyter nbextension enable --py widgetsnbextension
```
and then restarting your notebook?

**Comment by n01r** [comment]
Didn't work ^^; same behavior

**Comment by RemiLehe** [comment]
Yes, sorry I misunderstood your issue. I can now reproduce the issue that you have.
I'll let you know once I find a solution.

In the meanwhile, I think that downgrading to ipywidgets 6 would fix your issue.

**Comment by RemiLehe** [comment]
Or another option is to use `%matplotlib` or `%matplotlib notebook` intead of `%matplotlib inline`

**Comment by n01r** [comment]
Thanks! Well, using `%matplotlib notebook` already fixes it so the solution to this it not time-critical. :+1:

**Comment by RemiLehe** [comment]
The new version of openPMD-viewer will now issue a warning in this configuration (see PR #176).

To answer one of @ax3l's questions: the disappearance of the `slider` is explained by the [release note of ipywidgets 7](https://ipywidgets.readthedocs.io/en/stable/changelog.html):
```
Widgets are now displayed in the output area in the classic notebook and are treated as any other output. This allows the widgets to work more naturally with other cell output. To delete a widget, clear the output from the cell. Output from functions triggered by a widget view is appended to the output area that contains the widget view. This means that printed text will be appended to the output, and calling clear_output() will delete the entire output, including the widget view.
```
In the case of `openPMD-viewer`, when the user had `%matplotlib inline`, the plots are appended to the output area (resulting, by default, in more and more plots stacking in the output area, as the user uses the slider). In order to avoid this stacking, `openPMD-viewer` calls `clear_output` in this case. With previous versions of `ipywidgets`, this only cleared the plots (to make room for new plots), but now with `ipywidgets 7` the slider also gets cleared.

In the new version of `openPMD-viewer`, `clear_output` is **not** called when  the `ipywidgets` version is 7.
