### ISSUE TITLE
openPMD-viewer plot issue

### ISSUE THREAD

**Issue by QJohn2017** [openPMD/openPMD-viewer#249]
Hi, When I using the Warp PIC code to do the simulation and using the openPMD-viewer to postprocess the resutls, I got the below issue:
![image](https://user-images.githubusercontent.com/31507149/69722668-addaa780-1152-11ea-8c2b-9a4a64ad40ec.png)
It seems that there are electrons injected into the bubble, but its longitudinal momentum is very large,   it can be seen that it is nearly 5e29, which is unreasonable. So, I think it is an issue to be solved, can any one help me?

**Comment by ax3l** [comment]
Thank you for the report!
Which versions of Warp and openPMD-viewer did you use?

**Comment by QJohn2017** [comment]
@ax3l , Thank you for your reply! The Warp version I used  is the latest, and the openPMD-viewer version is 0.8.2. Do you doubt that the openPMD-viewer version I used is too old?

**Comment by QJohn2017** [comment]
@ax3l , another postprocess issue shows  as follows:
![image](https://user-images.githubusercontent.com/31507149/69782097-0eb5be80-11eb-11ea-972f-13e381aa5bde.png)
It can be seen that in the second picture, the particle distribution in z-x plane is very strange, but in theory, it should be the same as the first one.

**Comment by QJohn2017** [comment]
@ax3l @RemiLehe , the relevant input file of warp code simulation is shown in https://bitbucket.org/berkeleylab/warp/issues/61/warp-simulation-issue

**Comment by RemiLehe** [comment]
@QJohn2017 
My guess is that this is a bug in Warp, not in the `openPMD-viewer`. 
In order to confirm this, could you try to open the same file with [`openPMD-api`](https://openpmd-api.readthedocs.io/en/0.10.0-alpha/) instead of `openPMD-viewer` and check whether the momenta are still in the 5e29 range, with openPMD-api?

If you have any question on `openPMD-api`, please use [this issue tracker](https://github.com/openPMD/openPMD-api/issues).
