### ISSUE TITLE
Selection of particle position

### ISSUE THREAD

**Issue by StevE-Ong** [openPMD/openPMD-viewer#269]
Hi, I am plotting my LWFA simulation using openPMD. I intended to calculated the charge by using 
```
ts_2d.get_charge(iteration=40500,species='e_all',select={'y' : [970e-6,995e-6]})
0.0
```
by selecting the region between y=[970micron,995micron]. However, it returns zero charge.
After investigating, I find that the unit for the range is not in meter but in micron, which is not the case as described in the python code and the tutorials. Is this a bug?
```
ts_2d.get_particle( ['y'], species='e_all', iteration=40500)
[array([945.24822259, 945.34530999, 945.29339284, ..., 944.83532227,
        944.83807183, 944.99804099])] 
```

![Ex](https://user-images.githubusercontent.com/52823653/74534907-71426f00-4f3d-11ea-8eff-c69573676430.png)

**Comment by soerenjalas** [comment]
Hi,
older Versions of openPMD-viewer handled the particle positions in µm. However, since release 1.0 everything is in meters. 
See [the changelog](https://github.com/openPMD/openPMD-viewer/blob/master/CHANGELOG.mdl) for further information.
So if you update openPMD-viewer 
`ts_2d.get_charge(iteration=40500,species='e_all',select={'y' : [970e-6,995e-6]})` should work as expected.

**Comment by StevE-Ong** [comment]
I see there is a change there. Thanks.
