### ISSUE TITLE
3D plotting of trajectories

### ISSUE THREAD

**Issue by StanczakDominik** [openPMD/openPMD-viewer#270]
Hi, I'd forgotten about all about this project! :)

The python landscape for 3D plotting is slowly improving - I particularly like the [PyVista](https://docs.pyvista.org/) project. I'm already implementing 3D plots for mesh-free particle simulations in PlasmaPy, but I thought it might be a good idea to "upstream" that functionality and contribute it here.

Would you be interested in letting me contribute that?

**Comment by RemiLehe** [comment]
Sure, that would be very interesting!
One quick question: when plotting individual particles, can `pyvista` reasonably handle a large amount of particles (e.g. >1e6). I am asking because these are typical numbers for most `openPMD-viewer` users in the PIC community.

This large number of particles is also the reason why, for 2D plots, `openPMD-viewer` does not plot individual particles, but instead bins them on a 2D grid and uses `matplotlib.imshow` to plot the corresponding 2D histogram. (i.e. `matplotlib` is too slow when plotting ~1e6 particles individually)

**Comment by StanczakDominik** [comment]
Admittedly that's not exactly a scale I've considered! Based on [the examples](https://docs.pyvista.org/examples/00-load/create-point-cloud.html#sphx-glr-examples-00-load-create-point-cloud-py) it seems like it can handle ~60k points relatively easily. I haven't yet been able to test going above that.

A 3D histogram or [volume render](https://docs.pyvista.org/examples/02-plot/volume.html#sphx-glr-examples-02-plot-volume-py) could be a workaround, though.

**Comment by RemiLehe** [comment]
Yes, agreed, having 3D volume rendering capabilities in `openPMD-viewer` (for both fields on a mesh, and 3D particle histograms) would be really awesome!!

If you would like to contribute this capability, we are definitely interested! I can also help with questions and pointing out where the changes would need to be made.

**Comment by StanczakDominik** [comment]
Hey, I'm sorry, but I'm going to have to close this issue for now - as usual, I overestimated the time I have to commit to a project like this :sweat_smile:, and I don't want to clutter your repo.
