### ISSUE TITLE
h5 file size

### ISSUE THREAD

**Issue by cbontoiu** [openPMD/openPMD-viewer#273]
Many times I want to load the h5 files as my picongpu simulation is still running. I use
```
ts = OpenPMDTimeSeries(filePath + '/simOutput/h5/', check_all_files=False) 
```
The problem is that when loading the files, one of them is not complete. The trick I do is to watch its size growing and hopefully load the folder just when its size matches the size of the other files, that is this last file is complete and has a signature in it. 

However, when the size of the files is small (~350 MB) they are written to disk so fast that I can't catch that moment. It would be great to add the possibility to load only files which have a certain size. Is there any way to achieve this?

thank you,
Cristian

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

The original problem should be fixed by #262 (which does not check the size, but instead simply skips unreadable files - such as files that currently being written). This is not yet part of the latest release of `openPMD-viewer`, but you can still test it by doing:
```
pip uninstall openPMD-viewer
pip install git+https://github.com/openPMD/openPMD-viewer.git@dev
```

Could you confirm that this fixes the issue?

**Comment by cbontoiu** [comment]
Yes it works,
Great! Thank you!

![image](https://user-images.githubusercontent.com/7108691/76238495-d67d3d80-6227-11ea-9386-59911856ba05.png)

**Comment by RemiLehe** [comment]
Nice! 
Thanks for checking!
