### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by zhangli28** [openPMD/openPMD-viewer#381]
Dear Developers,

I am wondering about tracking of particles

**Comment by RemiLehe** [comment]
Thanks for pointing this out.
I don't know of anyone using Ocelot in combination with FBPIC or WarpX (we usually use [ImpactX](https://github.com/ECP-WarpX/impactx) for tracking), but it should definitely be possible, as you pointed out.
If you try doing so, feel free to post any questions you may have in the process :)

**Comment by soerenjalas** [comment]
@AngelFP might have some insights.

**Comment by AngelFP** [comment]
I have done this with FBPIC+Ocelot and Wake-T+Ocelot. With Wake-T it is quite straightforward because because Ocelot already has built-in converters between the two codes ([link](https://github.com/ocelot-collab/ocelot/blob/master/ocelot/adaptors/wake_t.py)) so that you don't even need to save the data to disk to couple them. With FBPIC, I read the particle data using [this](https://github.com/AngelFP/APtools/blob/e38b9398189bd0648913a3f0d3960e8539450512/aptools/particle_distributions/read.py#L13C11-L13C11) and then make an Ocelot `ParticleArray` by hand. It looks like the function you discovered could do this in one step.

**Comment by zhangli28** [comment]
Thank you all (@RemiLehe @soerenjalas @AngelFP ) for help and sorry for late reply. I was struck in flood in my home town in august. 
@AngelFP mentioned that with Wake-T it is easy to convert in Ocelot. My question to @AngelFP is can it be possible to convert from FBPIC to Wake-T format because just 2 days ago I came to know from Andrei that Wake-T can also be used for particle tracking.
@AngelFP can you help me to understand how I can use Wake-T to do particle tracking for beam transportation line using FBPIC simuation data.

**Comment by AngelFP** [comment]
Hi @zhangli28, sorry to hear about the flooding, I hope you were safe!

You can read an FBPIC beam into Wake-T using the following code:

```python
from wake_t.utilities.bunch_generation import get_from_file

bunch = get_from_file(file_path='path/to/file.h5', data_format='openpmd', species_name='species_name')
```

For making a simulation of the transport line you can check the example [here](https://wake-t.readthedocs.io/en/latest/tutorials/02_plasma_beamline_simulation.html#sphx-glr-tutorials-02-plasma-beamline-simulation-py) (which consists of a drift followed by a plasma lens), starting at [Create beam capture section](https://wake-t.readthedocs.io/en/latest/tutorials/02_plasma_beamline_simulation.html#create-beam-capture-section), since you don't need to simulate the LPA.

**Comment by zhangli28** [comment]
Hi @AngelFP , 

thank you so much for your help. I will definitely check Wake-T and it further applications in combination with FBPIC. 

Thanks to all of you great guys (@AngelFP @RemiLehe @soerenjalas).
