### ISSUE TITLE
wget in tutorials not a standard python (2.7) module

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#40]
Hi,
this is really a minor thing: I noticed that my anaconda python does not ship with wget, which is used to download the sample data in the tutorials. I'm not sure if this is the case because my anaconda is outdated or if this is standard. 
This could maybe lead to some confusion for inexperienced python users. I think adding it to the `requirements.txt` is a little bit overkill, since it is technically not needed for the viewer itself, but we could maybe add a side note in the tutorials.
If wget now comes with python, forget all I've said above :)

**Comment by ax3l** [comment]
> I think adding it to the requirements.txt is a little bit overkill

imho, just add it. that is not a heavy dependency :)

**Comment by RemiLehe** [comment]
Hi Soeren,

In principle, wget should be installed when you run "python setup.py install", because it is added to the dependencies within setup.py (see the code of this file). Could you try to do "python setup.py install" again, just to check whether wget gets installed or not ?

The reason that I did not include wget in requirements.txt (but in setup.py instead) is precisely because conda cannot handle it. More precisely, if a user tries to do "conda install --file requirements.txt" and wget is inside the file, the command will fail. (One could say that it is better for the user to do "pip install -r requirements.txt", since this would not fail with wget, but in this case h5py does not get installed properly.)

If you have any suggestion on how to better organize this, let me know. Also, I think I should probably add some text in README.txt to say that the dependencies should be installed with "conda install --file requirements.txt".

**Comment by soerenjalas** [comment]
Oh I didn't see that it was included in setup.py. This was done quite recently, right? I guess I didn't use the current commit. With the newest one, everything works like a charm. So I think we can leave it as it is. Sorry for the trouble.

**Comment by RemiLehe** [comment]
No problem :) I'm glad it works. 
Also, this was indeed added recently. 

You can close the issue if you are satisfied with the current implementation.

**Comment by ax3l** [comment]
ah of course you are right @RemiLehe, we just added it in #34 ;)
