### ISSUE TITLE
Get_fields returns extents in different order than the field array

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#8]
I noticed an unexpected behaviour in how `get_fields` returns the fields and the extent of the fields: 
while the extents are returned as (z_min, z_max, r_min, r_max), or similar for other coordinates, the shape of the field array is (Nr, Nz). In other words "flipped" in order. I think this behaviour can lead to confusion and we should, if we don't change this, at least explicitly mention the structure of the returned quantities in the docstring.

**Comment by RemiLehe** [comment]
Yes, I agree this is very confusing, and it should be changed. 

The easiest solution would be to transpose the field array before returning it, so that when you do
`rho, extent = ts.get_field('rho')`, then `rho` is of shape `(Nz, Nr)`, and extent is still (zmin, zmax, rmin, rmax).

The problem with changing is that:
- Transposition may be expensive (especially if you are writing a script that plots hundreds of figures)
- With the transposed array, people will have to retranspose it when using imshow :
`plt.imshow( rho.T , extent=extent )`

What is your opinion? Should we do the transpose, or not do it and document the confusing way in which the array is returned ?

**Comment by soerenjalas** [comment]
I agree with you that transposing the array is an unreasonable approach, especially because users will have to transpose again before plotting. This feels really unnatural. However, I was thinking about changing the order of the extents accordingly. Can you think of anything speaking against this?
Otherwise I think documenting the behaviour is the best solution for now.

**Comment by RemiLehe** [comment]
Actually if you swap the order of the extent, than that means the user has to do 
`plt.imshow( rho, extent = [ extent[2], extent[3], extent[0], extent[1] ] )`
So, in fact, the reason why the output of the `get_field` is counterintuitive is because the `imshow` command is also counterintuitive. 

It seems there is no perfect solution, but maybe documenting the current implementation in docstrings and in the tutorials can be a temporary solution until we figure out something more clever. 

Another solution (as discussed also by @PrometheusPi in the previous repository) maybe to return, instead of a 4-element array, an object that contains several useful arrays like `extent` (correct ordering that matches the axes of the array), `imshow_extent` (reverse ordering for imshow)...), as well as the 1d array of the z positions and r positions of the grid, which are also very useful and are not currently returned. Another advantage of that solution would be that we can always extend that object with new attributes (as we progressively discover the attributes ), without changing the basic API of `get_field`.
What do you think ?

**Comment by soerenjalas** [comment]
Ok I see the problem is indeed with imshow. I think the last option seems to be a good plan down the road and for now we should make sure to document the current behaviour of the method appropriately.

**Comment by RemiLehe** [comment]
Ok, I can take care of that, probably by the end of the week. 
I may actually implement the last solution, if it turns it is fast to do. 

Remi
